version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: elyar1996/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static/
      - media:/media/
  frontend:
    image: elyar1996/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/
  gateway:
    image: elyar1996/foodgram_gateway
    env_file: .env
    depends_on: 
      - backend
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

