# Generated by Django 3.2.16 on 2025-01-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={'verbose_name': 'короткая ссылка', 'verbose_name_plural': 'Короткие ссылки'},
        ),
    ]
