# Generated by Django 3.2.16 on 2024-12-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_shortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
