# Generated by Django 3.2.16 on 2024-12-20 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20241220_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
